--Tao bang BELONG va khoa chinh
CREATE TABLE BELONG
(
	departmentNo NUMBER NOT NULL,
	companyNo NUMBER NOT NULL
);
ALTER TABLE BELONG ADD CONSTRAINT PK_BELONG PRIMARY KEY (departmentNo, companyNo);

--4. Bang BELONG
INSERT INTO BELONG VALUES (1, 1);
INSERT INTO BELONG VALUES (2, 2);
INSERT INTO BELONG VALUES (3, 3);
INSERT INTO BELONG VALUES (4, 4);
INSERT INTO BELONG VALUES (5, 5);

ALTER TABLE BELONG ADD CONSTRAINT FK1_BELONG FOREIGN KEY (departmentNo) REFERENCES DEPARTMENT (departmentNo);
ALTER TABLE BELONG ADD CONSTRAINT FK2_BELONG FOREIGN KEY (companyNo) REFERENCES COMPANY (companyNo);
