--Tao bang EVALUATE_CO 
CREATE TABLE EVALUATE_CO
(
	companyNo NUMBER NOT NULL,
	applicantNo NUMBER NOT NULL,
	interviewScheduleNo NUMBER NOT NULL,
	mark_co NUMBER,
	comment_co VARCHAR2(2000),
	CHECK (mark_co BETWEEN 1 AND 5)
		 --1: Rat te,
		 --2: Khong hai long,
		 --3: Binh thuong,
		 --4: Hai long,
		 --5: Rat hai long
);

--Khoa chinh
ALTER TABLE EVALUATE_CO ADD CONSTRAINT PK_EVALUATE_CO PRIMARY KEY (companyNo, applicantNo,interviewScheduleNo);

--Khoa ngoai
ALTER TABLE EVALUATE_CO ADD CONSTRAINT FK1_EVALUATE_CO FOREIGN KEY (companyNo) REFERENCES COMPANY (companyNo);
ALTER TABLE EVALUATE_CO ADD CONSTRAINT FK2_EVALUATE_CO FOREIGN KEY (applicantNo) REFERENCES APPLICANT (applicantNo);
ALTER TABLE EVALUATE_CO ADD CONSTRAINT FK3_EVALUATE_CO FOREIGN KEY (interviewScheduleNo) REFERENCES INTERVIEW_SCHEDULE (interviewScheduleNo);

--Du lieu
Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (21,22,41,5,'Công ty đón tiếp chu đón');
Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (21,23,43,4,'Cơ sở vật chất tốt');

Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (22,22,42,4,'Công ty có nhiều tiện nghi');
Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (22,24,42,5,'Công ty có nhiều khu vực giải trí');
Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (22,25,43,5,'Lương thưởng tốt');

Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (23,24,44,3,'Câu hỏi công ty còn chưa thực tế');
Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (23,25,42,3,'Nhiều khu vực công ty còn sơ sài');
Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (23,26,41,4,'Công ty có nhiều phòng ban ');

Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (24,29,65,5,'Công ty đẹp');
Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (24,30,66,5,'Thuận lợi cho việc di chuyển');
Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (24,31,67,5,'Công ty có hỗ trợ làm việc tại nhá');

Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (25,27,70,2,'Công ty tiếp đón còn kém');
Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (25,28,71,2,'Không có hướng dẫn rõ ràng về công việc');
Insert into EVALUATE_CO(COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (25,29,75,2,'Thông tin tuyển dụng còn chưa thực tế');

Insert into EVALUATE_CO (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_CO,COMMENT_CO) values (26,25,75,4,'Công ty uy tín');

Insert into EVALUATE_CO (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_CO,COMMENT_CO) values (27,26,65,3,'Công ty hỏi đúng trọng tâm công việc nhưng còn hơi sơ sài');

Insert into EVALUATE_CO (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_CO,COMMENT_CO) values (28,25,65,5,'Thông tin công việc đầy đủ');

Insert into EVALUATE_CO (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_CO,COMMENT_CO) values (29,30,67,5,'Công ty uy tín, đáng để làm việc');

Insert into EVALUATE_CO (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_CO,COMMENT_CO) values (30,25,42,4,'Tuyệt vời');
