--Tao bang EVALUATE_APL va khoa chinh
CREATE TABLE EVALUATE_APL
(
	companyNo NUMBER NOT NULL,
	applicantNo NUMBER NOT NULL,
	interviewScheduleNo NUMBER NOT NULL,
	mark_apl NUMBER,
	comment_apl VARCHAR2(2000),
	CHECK (mark_apl BETWEEN 1 AND 5)
		 --1: Rat te,
		 --2: Khong hai long,
		 --3: Binh thuong,
		 --4: Hai long,
		 --5: Rat hai long
);
ALTER TABLE EVALUATE_APL ADD CONSTRAINT PK_EVALUATE_APL PRIMARY KEY (companyNo, applicantNo, interviewScheduleNo);

--Khoa ngoai
--Bang EVALUATE_APL
ALTER TABLE EVALUATE_APL ADD CONSTRAINT FK1_EVALUATE_APL FOREIGN KEY (companyNo) REFERENCES COMPANY (companyNo);
ALTER TABLE EVALUATE_APL ADD CONSTRAINT FK2_EVALUATE_APL FOREIGN KEY (applicantNo) REFERENCES APPLICANT (applicantNo);
ALTER TABLE EVALUATE_APL ADD CONSTRAINT FK3_EVALUATE_APL FOREIGN KEY (interviewScheduleNo) REFERENCES INTERVIEW_SCHEDULE (interviewScheduleNo);

--Du lieu
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (21,22,41,5,'Ứng viên trung thực');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (21,23,43,4,'Ứng viên chưa có nhiều kinh nghiệm');

Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (22,22,42,4,'Ứng viên hơi lúng túng');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (22,24,42,5,'Ứng viên có thực lực');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (22,25,43,5,'Kỹ năng chuyên môn cao');

Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (23,24,44,3,'Không chuẩn bị chu đáo');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (23,25,42,3,'Thiếu kinh nghiệm chuyên môn');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (23,26,41,3,'Còn nhiều thiếu sót');

Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (24,29,65,5,'Kỹ năng giao tiếp tốt');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (24,30,66,5,'Kỹ năng giao tiếp kém');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (24,31,67,5,'Thụ động trong trả lời câu hỏi');

Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (25,27,70,2,'Kỹ năng giao tiếp kém, thụ động');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (25,28,71,2,'Kỹ năng giao tiếp tốt');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (25,29,75,2,'Kỹ năng giao tiếp kém, thụ động');

Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (26,25,75,4,'Có nhiều trải nghiệm');
Insert into EVALUATE_APL (COMPANYNO,APPLICANTNO,INTERVIEWSCHEDULENO,MARK_APL,COMMENT_APL) values (26,26,76,4,'Kinh nghiệm làm việc phong phú');
