--Tao bang HAVE va khoa chinh
CREATE TABLE HAVE
(
	skillNo NUMBER NOT NULL,
	applicantNo NUMBER NOT NULL,
	level_apl NUMBER,
	yearsOfExperience NUMBER,
	CHECK (level_apl BETWEEN 1 AND 6)
		 --1: Kem,
		 --2: Yeu,
		 --3: Trung binh,
		 --4: Kha,
		 --5: Gioi,
		 --6: Chuyen sau
);
ALTER TABLE HAVE ADD CONSTRAINT PK_HAVE PRIMARY KEY (skillNo, applicantNo);

--13. Bang HAVE
INSERT INTO HAVE VALUES (1, 3, 4, 5);
INSERT INTO HAVE VALUES (2, 2, 3, 3);
INSERT INTO HAVE VALUES (3, 4, 2, 1);
INSERT INTO HAVE VALUES (4, 5, 5, 8);
INSERT INTO HAVE VALUES (5, 1, 1, 1);

ALTER TABLE HAVE ADD CONSTRAINT FK1_HAVE FOREIGN KEY (skillNo) REFERENCES SKILL(skillNo);
ALTER TABLE HAVE ADD CONSTRAINT FK2_HAVE FOREIGN KEY (applicantNo) REFERENCES APPLICANT(applicantNo);