--Tao bang RECRUIT va khoa chinh
create table RECRUIT (
	departmentNo NUMBER NOT NULL,
  	positionNo NUMBER NOT NULL,
  	numberOfPersonnel NUMBER
);
ALTER TABLE RECRUIT ADD CONSTRAINT PK_RECRUIT PRIMARY KEY (departmentNo, positionNo);

--6. Bang RECRUIT
INSERT INTO RECRUIT VALUES (1, 5, 5);
INSERT INTO RECRUIT VALUES (2, 3, 1);
INSERT INTO RECRUIT VALUES (4, 3, 1);
INSERT INTO RECRUIT VALUES (2, 4, 3);
INSERT INTO RECRUIT VALUES (5, 2, 1);

ALTER TABLE RECRUIT ADD CONSTRAINT FK1_RECRUIT FOREIGN KEY (departmentNo) REFERENCES DEPARTMENT(departmentNo);
ALTER TABLE RECRUIT ADD CONSTRAINT FK2_RECRUIT FOREIGN KEY (positionNo) REFERENCES POSITION(positionNo);