--Tao bang REGISTER va khoa chinh
CREATE TABLE REGISTER
(
	interviewScheduleNo NUMBER NOT NULL,
	applicantNo NUMBER NOT NULL,
	positionNo NUMBER NOT NULL,
	status NUMBER,
	CHECK (status BETWEEN 0 AND 4)
		-- 0: Da dang ky
		-- 1: Da huy dang ky
		-- 2: Da hoan thanh
		-- 3: Khong tham gia
		-- 4: Da duoc nhan vao lam
);
ALTER TABLE REGISTER ADD CONSTRAINT PK_REGISTER PRIMARY KEY (interviewScheduleNo, applicantNo, positionNo);

--14. Bang REGISTER
INSERT INTO REGISTER VALUES (1, 1, 2, 0);
INSERT INTO REGISTER VALUES (1, 3, 3, 1);
INSERT INTO REGISTER VALUES (1, 5, 1, 0);
INSERT INTO REGISTER VALUES (2, 2, 5, 0);
INSERT INTO REGISTER VALUES (2, 3, 4, 0);
INSERT INTO REGISTER VALUES (3, 1, 4, 0);
INSERT INTO REGISTER VALUES (3, 3, 1, 1);
INSERT INTO REGISTER VALUES (3, 4, 2, 0);
INSERT INTO REGISTER VALUES (3, 5, 5, 1);
INSERT INTO REGISTER VALUES (4, 2, 3, 0);
INSERT INTO REGISTER VALUES (4, 3, 1, 0);
INSERT INTO REGISTER VALUES (5, 2, 2, 0);
INSERT INTO REGISTER VALUES (5, 5, 3, 0);

ALTER TABLE REGISTER ADD CONSTRAINT FK1_REGISTER FOREIGN KEY (interviewScheduleNo) REFERENCES INTERVIEW_SCHEDULE (interviewScheduleNo);
ALTER TABLE REGISTER ADD CONSTRAINT FK2_REGISTER FOREIGN KEY (applicantNo) REFERENCES APPLICANT (applicantNo);
ALTER TABLE REGISTER ADD CONSTRAINT FK3_REGISTER FOREIGN KEY (positionNo) REFERENCES POSITION (positionNo);