create table REQUIRE (
	positionNo NUMBER NOT NULL,
  	requirementNo NUMBER NOT NULL,
	level_Re NUMBER,
	yearsOfExperience NUMBER,
	CHECK (level_Re BETWEEN 1 AND 6)
		 --1: Kem,
		 --2: Yeu,
		 --3: Trung binh,
		 --4: Kha,
		 --5: Gioi,
		 --6: Chuyen sau
);
ALTER TABLE REQUIRE ADD CONSTRAINT PK_REQUIRE PRIMARY KEY (positionNo, requirementNo);

INSERT INTO REQUIRE VALUES (1, 3, 2, NULL);
INSERT INTO REQUIRE VALUES (2, 1, 5, 4);
INSERT INTO REQUIRE VALUES (5, 4, 6, NULL);
INSERT INTO REQUIRE VALUES (4, 5, 3, 2);
INSERT INTO REQUIRE VALUES (3, 2, 4, 1);

ALTER TABLE REQUIRE ADD CONSTRAINT FK1_REQUIRE FOREIGN KEY (positionNo) REFERENCES POSITION(positionNo);
ALTER TABLE REQUIRE ADD CONSTRAINT FK2_REQUIRE FOREIGN KEY (requirementNo) REFERENCES REQUIREMENT(requirementNo);