CREATE DATABASE TEST
GO

USE TEST
GO

create table POSITION (
	positionNo TINYINT IDENTITY(1,1) NOT NULL,
  	positionName NVARCHAR(30) NOT NULL UNIQUE,
  	numberOfPersonnel TINYINT
);
ALTER TABLE POSITION ADD CONSTRAINT PK_POSITION PRIMARY KEY (positionNo);

create table REQUIREMENT (
	requirementNo TINYINT IDENTITY(1,1) NOT NULL,
  	requirementName NVARCHAR(50) NOT NULL UNIQUE,
  	yearsOfExperience TINYINT
);
ALTER TABLE REQUIREMENT ADD CONSTRAINT PK_REQUIREMENT PRIMARY KEY (requirementNo);

create table REQUIRE (
	positionNo TINYINT NOT NULL,
  	requirementNo TINYINT NOT NULL
);
ALTER TABLE REQUIRE ADD CONSTRAINT PK_REQUIRE PRIMARY KEY (positionNo, requirementNo);

create table SKILL (
	skillNo TINYINT IDENTITY(1,1) NOT NULL,
  	skillName NVARCHAR(50) NOT NULL UNIQUE,
  	applicantNo TINYINT,
  	level TINYINT,
  	yearsOfExperience TINYINT,
  	
  	CHECK (level BETWEEN 1 AND 5)
);
ALTER TABLE SKILL ADD CONSTRAINT PK_SKILL PRIMARY KEY (skillNo);

create table RECRUIT (
	departmentNo TINYINT NOT NULL,
  	positionNo TINYINT NOT NULL
);
ALTER TABLE RECRUIT ADD CONSTRAINT PK_RECRUIT PRIMARY KEY (departmentNo, positionNo);

INSERT INTO POSITION VALUES (N'Quản lý phòng nhân sự', 1);
INSERT INTO POSITION VALUES (N'Quản lý phòng kế toán', 1);
INSERT INTO POSITION VALUES (N'Trưởng ban bảo vệ', 1);
INSERT INTO POSITION VALUES (N'Editor', 3);
INSERT INTO POSITION VALUES (N'Nhân viên vệ sinh', 5);

INSERT INTO REQUIREMENT VALUES (N'Kế toán', 5);
INSERT INTO REQUIREMENT VALUES (N'Quản lý dự án', 7);
INSERT INTO REQUIREMENT VALUES (N'Ngoại ngữ', 4);
INSERT INTO REQUIREMENT VALUES (N'Tin học văn phòng', 3);
INSERT INTO REQUIREMENT VALUES (N'Lãnh đạo', 6);

INSERT INTO REQUIRE VALUES (1, 3)
INSERT INTO REQUIRE VALUES (2, 3)
INSERT INTO REQUIRE VALUES (2, 5)
INSERT INTO REQUIRE VALUES (1, 4)
INSERT INTO REQUIRE VALUES (3, 4)

INSERT INTO SKILL VALUES (N'Ngoại ngữ', 3, 4, 5);
INSERT INTO SKILL VALUES (N'Tin học văn phòng', 2, 3, 3);
INSERT INTO SKILL VALUES (N'Reporting', 4, 2, 1);
INSERT INTO SKILL VALUES (N'Quản lý dự án', 5, 5, 8);
INSERT INTO SKILL VALUES (N'Researching', 1, 1, 1);

INSERT INTO RECRUIT VALUES (1, 5);
INSERT INTO RECRUIT VALUES (2, 3);
INSERT INTO RECRUIT VALUES (4, 3);
INSERT INTO RECRUIT VALUES (2, 4);
INSERT INTO RECRUIT VALUES (5, 2);

ALTER TABLE REQUIRE ADD CONSTRAINT FK01_REQUIRE FOREIGN KEY (positionNo) REFERENCES POSITION(positionNo);
ALTER TABLE REQUIRE ADD CONSTRAINT FK02_REQUIRE FOREIGN KEY (requirementNo) REFERENCES REQUIREMENT(requirementNo);

ALTER TABLE SKILL ADD CONSTRAINT FK_SKILL FOREIGN KEY (applicantNo) REFERENCES APPLICANT(applicantNo);

ALTER TABLE RECRUIT ADD CONSTRAINT FK01_RECRUIT FOREIGN KEY (departmentNo) REFERENCES DEPARTMENT(departmentNo);
ALTER TABLE RECRUIT ADD CONSTRAINT FK02_RECRUIT FOREIGN KEY (positionNo) REFERENCES POSITION(positionNo);