create table POSITION (
	positionNo TINYINT IDENTITY(1,1) NOT NULL,
  	positionName NVARCHAR(30) NOT NULL UNIQUE,
  	numberOfPersonnel TINYINT
)
ALTER TABLE POSITION ADD CONSTRAINT PK_POSITION PRIMARY KEY (positionNo)
GO

INSERT INTO POSITION VALUES (N'Quản lý phòng nhân sự', 1)
INSERT INTO POSITION VALUES (N'Quản lý phòng kế toán', 1)
INSERT INTO POSITION VALUES (N'Trưởng ban bảo vệ', 1)
INSERT INTO POSITION VALUES (N'Editor', 3)
INSERT INTO POSITION VALUES (N'Nhân viên vệ sinh', 5)
GO