CREATE TABLE REGISTER
(
	interviewScheduleNo TINYINT NOT NULL,
	applicantNo TINYINT NOT NULL,
	positionNo TINYINT NOT NULL,
	status TINYINT,

	CHECK (status BETWEEN 0 AND 1)
)
ALTER TABLE REGISTER ADD CONSTRAINT PK_REGISTER PRIMARY KEY (interviewScheduleNo, applicantNo, positionNo)
GO

INSERT INTO REGISTER VALUES (1, 1, 2, 0)
INSERT INTO REGISTER VALUES (1, 3, 3, 1)
INSERT INTO REGISTER VALUES (1, 5, 1, 0)
INSERT INTO REGISTER VALUES (2, 2, 5, 0)
INSERT INTO REGISTER VALUES (2, 3, 4, 0)
INSERT INTO REGISTER VALUES (3, 1, 4, 0)
INSERT INTO REGISTER VALUES (3, 3, 1, 1)
INSERT INTO REGISTER VALUES (3, 4, 2, 0)
INSERT INTO REGISTER VALUES (3, 5, 5, 1)
INSERT INTO REGISTER VALUES (4, 2, 3, 0)
INSERT INTO REGISTER VALUES (4, 3, 1, 0)
INSERT INTO REGISTER VALUES (5, 2, 2, 0)
INSERT INTO REGISTER VALUES (5, 5, 3, 0)
GO

ALTER TABLE REGISTER ADD CONSTRAINT FK1_REGISTER FOREIGN KEY (interviewScheduleNo) REFERENCES INTERVIEW_SCHEDULE (interviewScheduleNo)
ALTER TABLE REGISTER ADD CONSTRAINT FK2_REGISTER FOREIGN KEY (applicantNo) REFERENCES APPLICANT (applicantNo)
ALTER TABLE REGISTER ADD CONSTRAINT FK3_REGISTER FOREIGN KEY (positionNo) REFERENCES POSITION (positionNo)
GO
