create table REQUIRE (
	positionNo TINYINT NOT NULL,
  	requirementNo TINYINT NOT NULL
)
ALTER TABLE REQUIRE ADD CONSTRAINT PK_REQUIRE PRIMARY KEY (positionNo, requirementNo)
GO

INSERT INTO REQUIRE VALUES (1, 3)
INSERT INTO REQUIRE VALUES (2, 3)
INSERT INTO REQUIRE VALUES (2, 5)
INSERT INTO REQUIRE VALUES (1, 4)
INSERT INTO REQUIRE VALUES (3, 4)
GO

ALTER TABLE REQUIRE ADD CONSTRAINT FK1_REQUIRE FOREIGN KEY (positionNo) REFERENCES POSITION(positionNo)
ALTER TABLE REQUIRE ADD CONSTRAINT FK2_REQUIRE FOREIGN KEY (requirementNo) REFERENCES REQUIREMENT(requirementNo)
GO