create table REQUIREMENT (
	requirementNo TINYINT IDENTITY(1,1) NOT NULL,
  	requirementName NVARCHAR(50) NOT NULL UNIQUE,
)
ALTER TABLE REQUIREMENT ADD CONSTRAINT PK_REQUIREMENT PRIMARY KEY (requirementNo)
GO

INSERT INTO REQUIREMENT VALUES (N'Kế toán')
INSERT INTO REQUIREMENT VALUES (N'Quản lý dự án')
INSERT INTO REQUIREMENT VALUES (N'Ngoại ngữ')
INSERT INTO REQUIREMENT VALUES (N'Tin học văn phòng')
INSERT INTO REQUIREMENT VALUES (N'Lãnh đạo')
GO
