create table SKILL (
	skillNo TINYINT IDENTITY(1,1) NOT NULL,
  	skillName NVARCHAR(50) NOT NULL UNIQUE,
  	applicantNo TINYINT,
  	level TINYINT,
  	yearsOfExperience TINYINT,
  	
  	CHECK (level BETWEEN 1 AND 5)
)
ALTER TABLE SKILL ADD CONSTRAINT PK_SKILL PRIMARY KEY (skillNo)
GO

INSERT INTO SKILL VALUES (N'Ngoại ngữ', 3, 4, 5)
INSERT INTO SKILL VALUES (N'Tin học văn phòng', 2, 3, 3)
INSERT INTO SKILL VALUES (N'Reporting', 4, 2, 1)
INSERT INTO SKILL VALUES (N'Quản lý dự án', 5, 5, 8)
INSERT INTO SKILL VALUES (N'Researching', 1, 1, 1)
GO

ALTER TABLE SKILL ADD CONSTRAINT FK_SKILL FOREIGN KEY (applicantNo) REFERENCES APPLICANT(applicantNo)
GO