CREATE TABLE EVALUATE_APL
(
	companyNo TINYINT NOT NULL,
	applicantNo TINYINT NOT NULL,
	point TINYINT,
	comment NVARCHAR(2000)
)
ALTER TABLE EVALUATE_APL ADD CONSTRAINT PK_EVALUATE_APL PRIMARY KEY (companyNo, applicantNo)
GO

INSERT INTO EVALUATE_APL VALUES (1, 1, 5, N'Ứng viên rất trung thực')
INSERT INTO EVALUATE_APL VALUES (1, 5, 5, N'Ứng viên đến đúng giờ')
INSERT INTO EVALUATE_APL VALUES (2, 2, 4, N'Ứng viên chưa có nhiều kinh nghiệm')
INSERT INTO EVALUATE_APL VALUES (2, 3, 4, N'Ứng viên hơi lúng túng')
INSERT INTO EVALUATE_APL VALUES (3, 1, 5, N'Ứng viên có thực lực')
INSERT INTO EVALUATE_APL VALUES (3, 4, 5, N'Kỹ năng chuyên môn cao')
INSERT INTO EVALUATE_APL VALUES (4, 2, 3, N'Không chuẩn bị chu đáo')
INSERT INTO EVALUATE_APL VALUES (4, 3, 5, N'Kỹ năng giao tiếp tốt')
INSERT INTO EVALUATE_APL VALUES (5, 2, 2, N'Kỹ năng giao tiếp kém, thụ động')
INSERT INTO EVALUATE_APL VALUES (5, 5, 4, N'Có nhiều trải nghiệm')
GO

ALTER TABLE EVALUATE_APL ADD CONSTRAINT FK1_EVALUATE_APL FOREIGN KEY (companyNo) REFERENCES COMPANY (companyNo)
ALTER TABLE EVALUATE_APL ADD CONSTRAINT FK2_EVALUATE_APL FOREIGN KEY (applicantNo) REFERENCES APPLICANT (applicantNo)
GO