CREATE TABLE INTERVIEWER
(
	interviewerNo TINYINT IDENTITY(1,1) NOT NULL,
	interviewerName NVARCHAR(30) NOT NULL,
	phoneNumber CHAR(10),
	gmail VARCHAR(30),
	companyNo TINYINT
)
ALTER TABLE INTERVIEWER ADD CONSTRAINT PK_INTERVIEWER PRIMARY KEY (interviewerNo)
GO

INSERT INTO INTERVIEWER VALUES (N'Trần Văn A', '0378009008' , 'tranvana@gmai.com.vn', 1)
INSERT INTO INTERVIEWER VALUES (N'Trần Văn B', '0378989238', 'tranvanb@gmai.com.vn', 2)
INSERT INTO INTERVIEWER VALUES (N'Nguyễn Minh C', '0378011108', 'nguyenminhc@gmai.com.vn', 3)
INSERT INTO INTERVIEWER VALUES (N'Lưu Quốc A', '0378123097', 'luuquoca@gmai.com.vn', 4)
INSERT INTO INTERVIEWER VALUES (N'Trần Minh D', '0374568088', 'tranminhd@gmai.com.vn', 5)
GO

ALTER TABLE INTERVIEWER ADD CONSTRAINT FK_INTERVIEWER FOREIGN KEY (companyNo) REFERENCES COMPANY (companyNo)
GO