CREATE DATABASE QLTIMVIEC
GO
USE QLTIMVIEC
GO
--Tao bang POSITION va khoa chinh
create table POSITION (
	positionNo TINYINT IDENTITY(1,1) NOT NULL,
  	positionName VARCHAR(30) NOT NULL UNIQUE,
  	numberOfPersonnel TINYINT
)
ALTER TABLE POSITION ADD CONSTRAINT PK_POSITION PRIMARY KEY (positionNo)
GO

--Tao bang REQUIREMENT va khoa chinh
create table REQUIREMENT (
	requirementNo TINYINT IDENTITY(1,1) NOT NULL,
  	requirementName VARCHAR(50) NOT NULL UNIQUE,
)
ALTER TABLE REQUIREMENT ADD CONSTRAINT PK_REQUIREMENT PRIMARY KEY (requirementNo)
GO

--Tao bang REQUIRE va khoa chinh
create table REQUIRE (
	positionNo TINYINT NOT NULL,
  	requirementNo TINYINT NOT NULL,
	level TINYINT,
	yearsOfExperience TINYINT,

	CHECK (level BETWEEN 1 AND 6)
		 --1: Kém,
		 --2: Yếu,
		 --3: Trung bình,
		 --4: Khá,
		 --5: Giỏi,
		 --6: Chuyên sâu
)
ALTER TABLE REQUIRE ADD CONSTRAINT PK_REQUIRE PRIMARY KEY (positionNo, requirementNo)
GO

--Tao bang SKILL va khoa chinh
create table SKILL (
	skillNo TINYINT IDENTITY(1,1) NOT NULL,
  	skillName VARCHAR(50) NOT NULL UNIQUE,
)
ALTER TABLE SKILL ADD CONSTRAINT PK_SKILL PRIMARY KEY (skillNo)
GO

--Tao bang RECRUIT va khoa chinh
create table RECRUIT (
	departmentNo TINYINT NOT NULL,
  	positionNo TINYINT NOT NULL
)
ALTER TABLE RECRUIT ADD CONSTRAINT PK_RECRUIT PRIMARY KEY (departmentNo, positionNo)
GO

--Tao bang APPLICANT va khoa chinh
CREATE TABLE APPLICANT
(
	applicantNo TINYINT IDENTITY(1,1) NOT NULL,
	applicantName VARCHAR(30),
	citizenID VARCHAR(12) UNIQUE,
	dateOfBirth DATE,
	gender TINYINT,
	address VARCHAR(60),
	phoneNumber VARCHAR(10),
	gmail VARCHAR(30) UNIQUE,
	AccountID TINYINT,

	CHECK (gender BETWEEN 0 AND 1) 
		--0 : Nam 
		--1 : Nu
)
ALTER TABLE APPLICANT ADD CONSTRAINT PK_APPLICANT PRIMARY KEY (applicantNo)
GO

--Tao bang HAVE va khoa chinh
CREATE TABLE HAVE
(
	skillNo TINYINT NOT NULL,
	applicantNo TINYINT NOT NULL,
	level TINYINT,
	yearsOfExperience TINYINT,

	CHECK (level BETWEEN 1 AND 6)
		 --1: Kém,
		 --2: Yếu,
		 --3: Trung bình,
		 --4: Khá,
		 --5: Giỏi,
		 --6: Chuyên sâu
)
ALTER TABLE HAVE ADD CONSTRAINT PK_HAVE PRIMARY KEY (skillNo, applicantNo)
GO

--Tao bang REGISTER va khoa chinh
CREATE TABLE REGISTER
(
	interviewScheduleNo TINYINT NOT NULL,
	applicantNo TINYINT NOT NULL,
	positionNo TINYINT NOT NULL,
	status TINYINT,

	CHECK (status BETWEEN 0 AND 1)
	-- Sai trong word
		-- 0: Đã đăng ký
		-- 1: Đã hủy đăng ký
)
ALTER TABLE REGISTER ADD CONSTRAINT PK_REGISTER PRIMARY KEY (interviewScheduleNo, applicantNo, positionNo)
GO

--Tao bang EVALUATE_APL va khoa chinh
CREATE TABLE EVALUATE_APL
(
	companyNo TINYINT NOT NULL,
	applicantNo TINYINT NOT NULL,
	point TINYINT,
	comment VARCHAR(2000),

	CHECK (point BETWEEN 1 AND 5),
		 --1: Rất tệ,
		 --2: Không hài lòng,
		 --3: Bình thường,
		 --4: Hài lòng,
		 --5: Rất hài lòng
)
ALTER TABLE EVALUATE_APL ADD CONSTRAINT PK_EVALUATE_APL PRIMARY KEY (companyNo, applicantNo)
GO

--Tao bang EVALUATE_CO va khoa chinh
CREATE TABLE EVALUATE_CO
(
	companyNo TINYINT NOT NULL,
	applicantNo TINYINT NOT NULL,
	point TINYINT,
	comment VARCHAR(2000),

	CHECK (point BETWEEN 1 AND 5),
		 --1: Rất tệ,
		 --2: Không hài lòng,
		 --3: Bình thường,
		 --4: Hài lòng,
		 --5: Rất hài lòng
)
ALTER TABLE EVALUATE_CO ADD CONSTRAINT PK_EVALUATE_CO PRIMARY KEY (companyNo, applicantNo)
GO

--Tao bang BELONG va khoa chinh
CREATE TABLE BELONG
(
	departmentNo TINYINT NOT NULL,
	companyNo TINYINT NOT NULL
)
ALTER TABLE BELONG ADD CONSTRAINT PK_BELONG PRIMARY KEY (departmentNo, companyNo)
GO

--Tao bang COMPANY va khoa chinh
CREATE TABLE COMPANY
(
	companyNo TINYINT IDENTITY(1,1) NOT NULL,
	companyName VARCHAR(50) NOT NULL UNIQUE,
	address VARCHAR(60),
	hotline CHAR(10),
	gmail VARCHAR(30),
	startDate DATE,
	AccountID TINYINT
)
ALTER TABLE COMPANY ADD CONSTRAINT PK_COMPANY PRIMARY KEY (companyNo)
GO
 
--Tao bang DEPARTMENT va khoa chinh
CREATE TABLE DEPARTMENT
(
	departmentNo TINYINT IDENTITY(1,1) NOT NULL,
	departmentName VARCHAR(30) NOT NULL UNIQUE,
	describe VARCHAR(2000)
)
ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (departmentNo)
GO

--Tao bang INTERVIEWER va khoa chinh
CREATE TABLE INTERVIEWER
(
	interviewerNo TINYINT IDENTITY(1,1) NOT NULL,
	interviewerName VARCHAR(30) NOT NULL,
	phoneNumber CHAR(10),
	gmail VARCHAR(30),
	companyNo TINYINT,
	AccountID TINYINT
)
ALTER TABLE INTERVIEWER ADD CONSTRAINT PK_INTERVIEWER PRIMARY KEY (interviewerNo)
GO

--Tao bang INTERVIEW_SCHEDULE va khoa chinh
CREATE TABLE INTERVIEW_SCHEDULE
(
	interviewScheduleNo TINYINT IDENTITY(1,1) NOT NULL,
	startTime DATE,
	endTime DATE,
	location  VARCHAR(60),
	status TINYINT,
	slot TINYINT,
	interviewerNo TINYINT,

	CHECK (status BETWEEN 0 AND 2)
		-- 0: Chưa hoàn thành
		-- 1: Đã hoàn thành
		-- 2: Đã đạt số lượng tối đa
)
ALTER TABLE INTERVIEW_SCHEDULE ADD CONSTRAINT PK_INTERVIEW_SCHEDULE PRIMARY KEY (interviewScheduleNo)
GO

-- Tạo bảng Account
CREATE TABLE ACCOUNT(
	AccountID TINYINT IDENTITY(1,1) NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	ROLE	 VARCHAR(20) NOT NULL
)
GO
ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACC PRIMARY KEY (AccountID)
GO
--Nhap lieu
SET DATEFORMAT DMY;
--1. Bang COMPANY
INSERT INTO COMPANY VALUES ('SamSung', 'Quan 1', '2839157310','samsung@gmai.com.vn', '30/01/2007',1)
INSERT INTO COMPANY VALUES ('Intel', 'Phu Nhuan', '8437363000','Intel@gmai.com.vn','21/02/2006',2)
INSERT INTO COMPANY VALUES ('Cocacola', 'Hai Phong', '0500233891','Cocacola@gmai.com.vn', '14/6/1996',3)
INSERT INTO COMPANY VALUES ('Petrolimex', 'Ha Noi', '1900363003','Petrolimex@gmai.com.vn', '22/6/2005',4)
INSERT INTO COMPANY VALUES ('Viettel', 'Ha Noi', '18008098','Viettel@gmai.com.vn','1/6/1989',5)

--2. Bang DEPARTMENT
INSERT INTO DEPARTMENT VALUES ('Phong nhan su', NULL)
INSERT INTO DEPARTMENT VALUES ('Phong ke toan', NUll)
INSERT INTO DEPARTMENT VALUES ('Quan ly du an', NUll) 
INSERT INTO DEPARTMENT VALUES ('Bao ve', NUll)
INSERT INTO DEPARTMENT VALUES ('Ke toan thue', NUll)

--3. Bang BELONG
INSERT INTO BELONG VALUES (1, 1)
INSERT INTO BELONG VALUES (2, 2)
INSERT INTO BELONG VALUES (3, 3)
INSERT INTO BELONG VALUES (4, 4)
INSERT INTO BELONG VALUES (5, 5)
GO

--4. Bang POSITION
INSERT INTO POSITION VALUES ('Quan ly phong nhan su', 1)
INSERT INTO POSITION VALUES ('Quan ly phong ke toan', 1)
INSERT INTO POSITION VALUES ('Truong ban bao ve', 1)
INSERT INTO POSITION VALUES ('Editor', 3)
INSERT INTO POSITION VALUES ('Nhan vien ve sinh', 5)
GO

--5. Bang RECRUIT
INSERT INTO RECRUIT VALUES (1, 5)
INSERT INTO RECRUIT VALUES (2, 3)
INSERT INTO RECRUIT VALUES (4, 3)
INSERT INTO RECRUIT VALUES (2, 4)
INSERT INTO RECRUIT VALUES (5, 2)
GO

--6. Bang REQUIREMENT
INSERT INTO REQUIREMENT VALUES ('Ke toan')
INSERT INTO REQUIREMENT VALUES ('Quan ly du an')
INSERT INTO REQUIREMENT VALUES ('Ngoai ngu')
INSERT INTO REQUIREMENT VALUES ('Tin hoc van phong')
INSERT INTO REQUIREMENT VALUES ('Lanh dao')
GO

--7. Bang REQUIRE
INSERT INTO REQUIRE VALUES (1, 3, 2, NULL)
INSERT INTO REQUIRE VALUES (2, 1, 5, 4)
INSERT INTO REQUIRE VALUES (5, 4, 6, NULL)
INSERT INTO REQUIRE VALUES (4, 5, 3, 2)
INSERT INTO REQUIRE VALUES (3, 2, 4, 1)
GO

--8. Bang INTERVIEWER
INSERT INTO INTERVIEWER VALUES ('Tran Van A', '0378009008' , 'tranvana@gmail.com.vn', 1,6)
INSERT INTO INTERVIEWER VALUES ('Tran Van B', '0378989238', 'tranvanb@gmail.com.vn', 2,7)
INSERT INTO INTERVIEWER VALUES ('Nguyen Minh C', '0378011108', 'nguyenminhc@gmail.com.vn', 3,8)
INSERT INTO INTERVIEWER VALUES ('Luu Quoc A', '0378123097', 'luuquoca@gmail.com.vn', 4,9)
INSERT INTO INTERVIEWER VALUES ('Tran Minh D', '0374568088', 'tranminhd@gmail.com.vn', 5,10)
GO

--9. Bang INTERVIEW_SCHEDULE
INSERT INTO INTERVIEW_SCHEDULE VALUES ('13/01/2021', '15/01/2021' , '71 Dinh Tien Hoang' , 0 , 20, 1)
INSERT INTO INTERVIEW_SCHEDULE VALUES ('13/02/2021', '19/02/2021' , '65/6 Ha Ton Quyen' , 1 , 20, 2)
INSERT INTO INTERVIEW_SCHEDULE VALUES ('26/01/2021', '05/02/2021', '15 Nguyen Tri Phuong' , 0 , 20, 2)
INSERT INTO INTERVIEW_SCHEDULE VALUES ('13/01/2021', '19/01/2021', '72 Ho Tung Mau' , 0 , 20, 4)
INSERT INTO INTERVIEW_SCHEDULE VALUES ('21/03/2021', '05/04/2021', '79/5/1 Nguyen Thai Hoc' , 0 , 20, 5)
GO

--10. Bang APPLICANT
INSERT INTO APPLICANT VALUES ('Nguyen Hoai Linh', '079202009176', '23/04/2002', 1, '68/23 Dong Den', '070786884','linhhoainguyen2002@gmail.com',11)
INSERT INTO APPLICANT VALUES ('Nguyen Anh Kiet', '079202005713', '21/07/2002', 1, '76/3 Nguyen Trai', '0787264822','nguyenanhkiet2002@gmail.com',12)
INSERT INTO APPLICANT VALUES ('Nguyen Thanh Phat', '079202067492', '7/9/2001', 1, '11/6/8 Truong Cong Dinh', '0387518022','thanhphatnguyen2001@gmail.com',13)
INSERT INTO APPLICANT VALUES ('Nguyen Thi Thao Hong', '079202001436', '11/3/1998', 0, '227 Nguyen Thi Minh Khai', '0275784426','thaohongnt2001@gmail.com',14)
INSERT INTO APPLICANT VALUES ('Vu Thi Phuong Linh', '079202008648','16/6/2001', 0, '61 Dong Da', '0909666371','vtplinh2k1@gmail.com',15)
INSERT INTO APPLICANT VALUES ('Tran Thi My Nhung', '080202009171', '25/9/1999', 0, '89 Nguyen Van Cu', '0163787333','nhungtranthimy@gmail.com',16)
INSERT INTO APPLICANT VALUES ('Tran Quoc Trung', '077202009679','11/11/2000', 1, '22/6 Nguyen Ba Tong', '0193882563','trungquoctran@gmail.com',17)
GO

--11. Bang SKILL
INSERT INTO SKILL VALUES ('Ngoai ngu')
INSERT INTO SKILL VALUES ('Tin hoc van phong')
INSERT INTO SKILL VALUES ('Reporting')
INSERT INTO SKILL VALUES ('Quan ly du an')
INSERT INTO SKILL VALUES ('Researching')
GO

--12. Bang HAVE
INSERT INTO HAVE VALUES (1, 3, 4, 5)
INSERT INTO HAVE VALUES (2, 2, 3, 3)
INSERT INTO HAVE VALUES (3, 4, 2, 1)
INSERT INTO HAVE VALUES (4, 5, 5, 8)
INSERT INTO HAVE VALUES (5, 1, 1, 1)
GO

--13. Bang REGISTER
INSERT INTO REGISTER VALUES (1, 1, 2, 0)
INSERT INTO REGISTER VALUES (1, 3, 3, 1)
INSERT INTO REGISTER VALUES (1, 5, 1, 0)
INSERT INTO REGISTER VALUES (2, 2, 5, 0)
INSERT INTO REGISTER VALUES (2, 3, 4, 0)
INSERT INTO REGISTER VALUES (3, 1, 4, 0)
INSERT INTO REGISTER VALUES (3, 3, 1, 1)
INSERT INTO REGISTER VALUES (3, 4, 2, 0)
INSERT INTO REGISTER VALUES (3, 5, 5, 1)
INSERT INTO REGISTER VALUES (4, 2, 3, 0)
INSERT INTO REGISTER VALUES (4, 3, 1, 0)
INSERT INTO REGISTER VALUES (5, 2, 2, 0)
INSERT INTO REGISTER VALUES (5, 5, 3, 0)
GO

--14. Bang EVALUATE_APL
INSERT INTO EVALUATE_APL VALUES (1, 1, 5, 'Ung vien rat trung thuc')
INSERT INTO EVALUATE_APL VALUES (1, 5, 5, 'Ung vien rat dung gio')
INSERT INTO EVALUATE_APL VALUES (2, 2, 4, 'Ung vien chua co nhieu kinh nghiem')
INSERT INTO EVALUATE_APL VALUES (2, 3, 4, 'Ung vien hoi lung tung')
INSERT INTO EVALUATE_APL VALUES (3, 1, 5, 'Ung vien co thuc luc')
INSERT INTO EVALUATE_APL VALUES (3, 4, 5, 'Ky nang chuyen mon cao')
INSERT INTO EVALUATE_APL VALUES (4, 2, 3, 'Khong chuan bi chu dao')
INSERT INTO EVALUATE_APL VALUES (4, 3, 5, 'Ky nang giao tiep tot')
INSERT INTO EVALUATE_APL VALUES (5, 2, 2, 'Ky nang giao tiep kem, thu dong')
INSERT INTO EVALUATE_APL VALUES (5, 5, 4, 'Co nhieu trai nghiem')

--15. Bang EVALUATE_CO
INSERT INTO EVALUATE_CO VALUES (1, 1, 5, 'Cong ty co co so vat chat tot')
INSERT INTO EVALUATE_CO VALUES (1, 5, 4, 'Cong ty uy tin')
INSERT INTO EVALUATE_CO VALUES (2, 2, 4, 'Moi truong than thien')
INSERT INTO EVALUATE_CO VALUES (2, 3, 4, 'Cong ty don tiep chu dao')
INSERT INTO EVALUATE_CO VALUES (3, 1, 4, 'Cong ty uy tin')
INSERT INTO EVALUATE_CO VALUES (3, 4, 5, 'Cong ty cung cap day du thong tin ve cong viec')
INSERT INTO EVALUATE_CO VALUES (4, 2, 3, 'Cong ty hoi dung trong tam cong viec')
INSERT INTO EVALUATE_CO VALUES (4, 3, 5, 'Cong tu ut tin, rat dang de lam viec')
INSERT INTO EVALUATE_CO VALUES (5, 2, 2, 'Cong ty thieu chuyen nghiep, phong van so sai')
INSERT INTO EVALUATE_CO VALUES (5, 5, 4, 'Tuyet voi')
GO
--16. Bang ACCOUNT
INSERT INTO ACCOUNT VALUES('samsung','s123','Cong ty');
INSERT INTO ACCOUNT VALUES('intel','i123','Cong ty');
INSERT INTO ACCOUNT VALUES('cocacola','c123','Cong ty');
INSERT INTO ACCOUNT VALUES('petrolimex','p123','Cong ty');
INSERT INTO ACCOUNT VALUES('viettel','v123','Cong ty');	
INSERT INTO ACCOUNT VALUES ('tranva','a123','Nha tuyen dung');
INSERT INTO ACCOUNT VALUES ('tranvb','b123','Nha tuyen dung');
INSERT INTO ACCOUNT VALUES ('nguyenmc','c123','Nha tuyen dung');
INSERT INTO ACCOUNT VALUES ('luuqa','a1234','Nha tuyen dung');
INSERT INTO ACCOUNT VALUES ('tranmd','d123','Nha tuyen dung');
INSERT INTO ACCOUNT VALUES ('thaohong','thaohong123','Ung vien');
INSERT INTO ACCOUNT VALUES ('thanhphat','thanhphat123','Ung vien');
INSERT INTO ACCOUNT VALUES ('hoailinh','hoailinh123','Ung vien');
INSERT INTO ACCOUNT VALUES ('anhkiet','anhkiet123','Ung vien');
INSERT INTO ACCOUNT VALUES ('mynhung','mynhung123','Ung vien');
INSERT INTO ACCOUNT VALUES ('phuonglinh','phuonglinh123','Ung vien');
INSERT INTO ACCOUNT VALUES ('quoctrung','quoctrung123','Ung vien');

--Tao khoa ngoai
--Bang REQUIRE
ALTER TABLE REQUIRE ADD CONSTRAINT FK1_REQUIRE FOREIGN KEY (positionNo) REFERENCES POSITION(positionNo)
ALTER TABLE REQUIRE ADD CONSTRAINT FK2_REQUIRE FOREIGN KEY (requirementNo) REFERENCES REQUIREMENT(requirementNo)
GO

--Bang HAVE
ALTER TABLE HAVE ADD CONSTRAINT FK1_HAVE FOREIGN KEY (skillNo) REFERENCES SKILL(skillNo)
ALTER TABLE HAVE ADD CONSTRAINT FK2_HAVE FOREIGN KEY (applicantNo) REFERENCES APPLICANT(applicantNo)
GO

--Bang RECRUIT
ALTER TABLE RECRUIT ADD CONSTRAINT FK1_RECRUIT FOREIGN KEY (departmentNo) REFERENCES DEPARTMENT(departmentNo)
ALTER TABLE RECRUIT ADD CONSTRAINT FK2_RECRUIT FOREIGN KEY (positionNo) REFERENCES POSITION(positionNo)
GO

--Bang REGISTER
ALTER TABLE REGISTER ADD CONSTRAINT FK1_REGISTER FOREIGN KEY (interviewScheduleNo) REFERENCES INTERVIEW_SCHEDULE (interviewScheduleNo)
ALTER TABLE REGISTER ADD CONSTRAINT FK2_REGISTER FOREIGN KEY (applicantNo) REFERENCES APPLICANT (applicantNo)
ALTER TABLE REGISTER ADD CONSTRAINT FK3_REGISTER FOREIGN KEY (positionNo) REFERENCES POSITION (positionNo)
GO

--Bang EVALUATE_APL
ALTER TABLE EVALUATE_APL ADD CONSTRAINT FK1_EVALUATE_APL FOREIGN KEY (companyNo) REFERENCES COMPANY (companyNo)
ALTER TABLE EVALUATE_APL ADD CONSTRAINT FK2_EVALUATE_APL FOREIGN KEY (applicantNo) REFERENCES APPLICANT (applicantNo)
GO

--Bang EVALUATE_CO
ALTER TABLE EVALUATE_CO ADD CONSTRAINT FK1_EVALUATE_CO FOREIGN KEY (companyNo) REFERENCES COMPANY (companyNo)
ALTER TABLE EVALUATE_CO ADD CONSTRAINT FK2_EVALUATE_CO FOREIGN KEY (applicantNo) REFERENCES APPLICANT (applicantNo)
GO

--Bang BELONG
ALTER TABLE BELONG ADD CONSTRAINT FK1_BELONG FOREIGN KEY (departmentNo) REFERENCES DEPARTMENT (departmentNo)
ALTER TABLE BELONG ADD CONSTRAINT FK2_BELONG FOREIGN KEY (companyNo) REFERENCES COMPANY (companyNo)
GO

--Bang INTERVIEWER
ALTER TABLE INTERVIEWER ADD CONSTRAINT FK_INTERVIEWER FOREIGN KEY (companyNo) REFERENCES COMPANY (companyNo)
GO

--Bang INTERVIEW_SCHEDULE
ALTER TABLE INTERVIEW_SCHEDULE ADD CONSTRAINT FK_INTERVIEW_SCHEDULE FOREIGN KEY (interviewerNo) REFERENCES INTERVIEWER (interviewerNo)
GO

-- Bang COMPANY
ALTER TABLE COMPANY ADD CONSTRAINT FK_COMPANY_ACCOUNT FOREIGN KEY (AccountID) REFERENCES ACCOUNT (AccountID);


-- Bang INTERVIEWER
ALTER TABLE INTERVIEWER ADD CONSTRAINT FK_INTERVIEWER_ACCOUNT FOREIGN KEY (AccountID) REFERENCES ACCOUNT (AccountID);

-- BANG APPLICANT
ALTER TABLE APPLICANT ADD CONSTRAINT FK_APPLICANT_ACCOUNT FOREIGN KEY (AccountID) REFERENCES ACCOUNT (AccountID);