CREATE TABLE DEPARTMENT
(
	departmentNo TINYINT IDENTITY(1,1) NOT NULL,
	departmentName NVARCHAR(30) NOT NULL UNIQUE,
	describe NVARCHAR(2000)
)
ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (departmentNo)
GO

INSERT INTO DEPARTMENT VALUES (N'Phòng nhân sự', NULL)
INSERT INTO DEPARTMENT VALUES (N'Phòng kế toán', NUll)
INSERT INTO DEPARTMENT VALUES (N'Quản lý dự án', NUll) 
INSERT INTO DEPARTMENT VALUES (N'Bảo vệ', NUll)
INSERT INTO DEPARTMENT VALUES (N'Kế toán thuế', NUll)