create table RECRUIT (
	departmentNo TINYINT NOT NULL,
  	positionNo TINYINT NOT NULL
)
ALTER TABLE RECRUIT ADD CONSTRAINT PK_RECRUIT PRIMARY KEY (departmentNo, positionNo)
GO

INSERT INTO RECRUIT VALUES (1, 5)
INSERT INTO RECRUIT VALUES (2, 3)
INSERT INTO RECRUIT VALUES (4, 3)
INSERT INTO RECRUIT VALUES (2, 4)
INSERT INTO RECRUIT VALUES (5, 2)
GO

ALTER TABLE RECRUIT ADD CONSTRAINT FK1_RECRUIT FOREIGN KEY (departmentNo) REFERENCES DEPARTMENT(departmentNo)
ALTER TABLE RECRUIT ADD CONSTRAINT FK2_RECRUIT FOREIGN KEY (positionNo) REFERENCES POSITION(positionNo)
GO