create table SKILL (
	skillNo TINYINT IDENTITY(1,1) NOT NULL,
  	skillName NVARCHAR(50) NOT NULL UNIQUE,
)
ALTER TABLE SKILL ADD CONSTRAINT PK_SKILL PRIMARY KEY (skillNo)
GO

INSERT INTO SKILL VALUES (N'Ngoại ngữ')
INSERT INTO SKILL VALUES (N'Tin học văn phòng')
INSERT INTO SKILL VALUES (N'Reporting')
INSERT INTO SKILL VALUES (N'Quản lý dự án')
INSERT INTO SKILL VALUES (N'Researching')
GO

